### ISSUE TITLE
Does not work on Cinnamon 3.4.4 LM 18.2

### ISSUE THREAD

**Issue by Marcosdw** [germanfr/cinnamon-transparent-panels#11]
Hello, 

Does not work on Cinnamon 3.4.4 LM 18.2

Thank's fix

____
Sorry I use an online translator French English

**Comment by germanfr** [comment]
Hi, can you give me some details? It's working fine here.

**Comment by germanfr** [comment]
I'm closing this since it seems to be a duplicate of #10

**Comment by Marcosdw** [comment]
Delete all files Transparent panels
reinstall 
work fine
