### ISSUE TITLE
where is the english locale?

### ISSUE THREAD

**Issue by x4m3** [germanfr/cinnamon-transparent-panels#14]
i'm looking at the `transparent-panels@germanfr/po` directory, to make a new translation file, i can't find a `en.pot` file.  
do i need to base my translation file off `transparent-panels.pot` ?

it would be nice to have a "template" file to know where to start .

**Comment by germanfr** [comment]
There is no `en.pot`, it's called `transparent-panels.pot` (it's the only pot file in there).
Anyways, if you're going to translate it into french can you wait a couple of days? I'm going to release some new feature and it'll have new strings that will need to be translated too. Thanks :)

**Comment by x4m3** [comment]
sure

ping me when you're ready

**Comment by germanfr** [comment]
@x4m3 I think it's ready to go. The pot has been renamed to [transparent-panels@germanfr.pot](https://github.com/germanfr/cinnamon-transparent-panels/blob/master/transparent-panels%40germanfr/po/transparent-panels%40germanfr.pot) following what all other xlets do.
