### ISSUE TITLE
No JS module 'extensions' found in search path

### ISSUE THREAD

**Issue by venatiodecorus** [germanfr/cinnamon-transparent-panels#17]
I'm getting the following error when trying to start the extension on Cinnamon 3.4.6 and Ubuntu 17.10.

```
error t=2018-03-07T18:39:49Z No JS module 'extensions' found in search path
error t=2018-03-07T18:39:49Z [Extension "transparent-panels@germanfr"]: Error importing extension.js from transparent-panels@germanfr
error t=2018-03-07T18:39:49Z Could not load extension transparent-panels@germanfr
```

**Comment by germanfr** [comment]
That's because 3.4 is not currently supported. Try updating to 3.6 or download the latest release compatible with 3.4 from [here](https://github.com/germanfr/cinnamon-transparent-panels/releases).

**Comment by venatiodecorus** [comment]
Thank you, I appreciate your replies.
