### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Marcosdw** [germanfr/cinnamon-transparent-panels#20]
Hello,

I just updated and it does not work anymore

see the screen : http://pix.toile-libre.org/upload/original/1523688692.png

thank you kindly fix the problem

Sorry, I use an online translator French / English

LM 18.3 cinnamon 3.6.7 kernel 4-15-0-13

**Comment by germanfr** [comment]
Please, disable the 'use current theme styles' switch and tell me if it works. That is only for supported themes, and currently only Railway does because it is a new feature.

**Comment by Marcosdw** [comment]
I disabled and it still does not work
see screen : http://pix.toile-libre.org/upload/original/1523714755.png

**Comment by germanfr** [comment]
Can you post the content of `~/.xsession-erros` and `~/.cinnamon/ glass.log`?

**Comment by germanfr** [comment]
Also try with the default theme.

**Comment by Marcosdw** [comment]
Default Thème not change same problem

glass.log : https://paste2.org/1JM9JZfe
.xsession-errors : https://paste2.org/JgxWU6vM

**Comment by germanfr** [comment]
You have lots of errors comming from third-party applets. Please disable all third-party applets and post the logs again just after restarting Cinnamon (Ctrl+Alt+Esc). Also with the default theme.

**Comment by germanfr** [comment]
Oh, I think I spotted it. Open transparent panel settings and click 'reset settings' in the upper right corner. Then restart Cinnamon (Ctrl+Alt+Esc).

**Comment by Marcosdw** [comment]
OK Problem solved, I reset the dashboard.
Thank you for your help ;)

**Comment by germanfr** [comment]
Just remember to do that every time you update any extension, applet, etc. :)
