### ISSUE TITLE
[Bug] Use Current Theme Style doesn't work unless panel transparency type is set to 'Fully Transparent'

### ISSUE THREAD

**Issue by feren** [germanfr/cinnamon-transparent-panels#21]
So, basically, turns out Use Current Theme Style ONLY works when the Type of transparency is 'Fully Transparent'. Using the latest version of this extension on Spices, on Cinnamon 3.8.

**Comment by germanfr** [comment]
That option is for supported themes only. What theme are you using? I recently added more classes to theme the transparency with shadow and semi transparent variants. You should file the issue against the theme author.

**Comment by feren** [comment]
Oh, my own Feren Theme, that had the old two sets of Panel Ones, didn't know you added more, may I mind asking which ones the new themeing things are called?

**Comment by germanfr** [comment]
https://github.com/germanfr/cinnamon-transparent-panels/blob/master/README.md#supported-themes

**Comment by germanfr** [comment]
I added them because you requested it 😅
