### ISSUE TITLE
How to deal with very light backgrounds?

### ISSUE THREAD

**Issue by Sadi58** [germanfr/cinnamon-transparent-panels#24]
This is probably an new feature (**enhancement**) request, not an issue really.

My favourite is **fully transparent mode**, but when the background (wallpaper) is very light  this becomes unusable. Then my second best choice is **transparency with shadow**, which works for some light backgrounds, but not always...
Therefore,  as I prefer the slideshow mode for the wallpaper, I switch to my last choice: **semi-transparency**. But here I have the same problem as manually tweaking the cinnamon.css file of the theme I use: the level of transparency set also effects the panel icons and texts which don't look so good in some cases...

So I wonder if there's anything you can do in this respect: Keeping panel icons & text solid at all times?

**Comment by germanfr** [comment]
The way this currently works is by adding a CSS class to the panel to make it transparent. Changing text colour is nearly impossible and irresponsible without themes support. What do you propose?

**Comment by germanfr** [comment]
What do you mean by keep them solid? Keep solid what?

**Comment by Sadi58** [comment]
Sorry, I mean keeping all panel icons and texts completely non-transparent...

**Comment by Sadi58** [comment]
It doesn't matter which theme I use (Arc, Mint-Y, etc.) or does it?
With (or without) the transparent-panels extension, at least some items (icons & texts)  on the panel have the same transparency as the panel itself: all applets like calendar, weather, user but not menu (third party app indicators are also solid like the menu icon). So, for example, it may become difficult to read the date (calendar applet) when the background below is very light.

**Comment by germanfr** [comment]
Oh I now I understand. But as I said, there is nothing I can do on my side. I already provide a way to prevent such kind of things but is up to each theme to use it or not. You can ask [Mint-Y](https://github.com/linuxmint/mint-themes) devs if they want to add support for this extension by removing the font opacity inside this style classes `panel-transparent`, `panel-transparent-with-shadow` and `panel-semi-transparent`. Hope you are lucky because I think they don't accept third party extensions in their CSS.

**Comment by germanfr** [comment]
But let me try something first to see if I can do something.

**Comment by Sadi58** [comment]
Thanks.
Meanwhile, I was glad to discover that Arc cinnamon theme for one displays those items non-transparent (unlike Mint-Y series), although I can't see any instance of "panel-transparent", "panel-transparent-with-shadow" or "panel-semi-transparent" in the css file.

**Comment by Sadi58** [comment]
Thanks a lot.
It seems I should better stick with cinnamon themes with opaque icons and text in the panel.
I tried adding three entries like this to cinnamon.css but it didn't work ;-) 
```
.panel-transparent-with-shadow {
  color: rgba(255, 255, 255, 1.00); }
```

**Comment by germanfr** [comment]
If it was that simpler I could have done it in the extension's CSS. That's why themes have to implement it themselves, because the color property has to be added to many elements. Anyways, you could try with 
```css
#panel.panel-top.panel-transparent-with-shadow,
#panel.panel-right.panel-transparent-with-shadow,
#panel.panel-bottom.panel-transparent-with-shadow,
#panel.panel-left.panel-transparent-with-shadow {
  color: rgba(255, 255, 255, 1.00); }
```

**Comment by Sadi58** [comment]
OK, thanks ;-)
