### ISSUE TITLE
Feature request: transparency per-panel area

### ISSUE THREAD

**Issue by CottonEaster** [germanfr/cinnamon-transparent-panels#26]
```
 * Cinnamon version: (cinnamon --version): 4.0.8
 * Attach log:       (/home/<username>/.xsession-errors): not relevant for this request.
 ```

**Issue**

Using your wonderful extension - which I think should be incorporated into Cinnamon - I see the following on my system, when there is a maximised window. (The picture below is a partial screenshot. Please attend to the bottom of the image.)

![image](https://user-images.githubusercontent.com/9998846/50304335-8e89c380-0487-11e9-9ae1-dd3f820746e6.png)

Now, that appearance is by (your) design. However, it would be really good were we able to make the _right_ and _left_ side of the panel transparent - _but not the centre_ - even when there is a maximised window. That way, the panel can act as a dock, i.e. such that there is a background to the icons but not to the unoccupied parts of the panel.

**Comment by germanfr** [comment]
I share your desires to do that but that's out of the scope of this extension. I don't want to create a chimera. That'd be better in another extension.
