### ISSUE TITLE
[Bug] Panel Opaqueness is not automatic when enabled

### ISSUE THREAD

**Issue by feren** [germanfr/cinnamon-transparent-panels#3]
The Panel Opaque Feature, when enabled, only makes the panel go black behind when Cinnamon is started with a maximised window, and isn't automatic unlike the other maximised panel portion of the extension...

This means that you either have an opaque panel on the Cinnamon Session, or a transparent one on the Cinnamon session

**Comment by germanfr** [comment]
I don't understand you. Can you write how to get the error step by step?

**Comment by feren** [comment]
@germanfr 
1. Turn it on, nothing happens when a window is maximised
2. Restart Cinnamon while a window is maximised
3. It'll now be opaque, try unmaximising the window, it's still opaque
4. Turn it off, nothing happens again

**Comment by germanfr** [comment]
I can reproduce steps one and four. I'll work on that. But I can't reproduce the whole sequence.

**Comment by feren** [comment]
@germanfr I'm on 3.0 if that helps

**Comment by germanfr** [comment]
Is there anything in the log?
Also check again. I've recently fixed some unrecognized maximized windows issues. Four is for other reasons so still not fixed.

**Comment by feren** [comment]
@germanfr It works now! Thanks... :)
