### ISSUE TITLE
UUID: transparent-panels@germanfr: Panels extension in Cinnamon: hardly different colors in panel edit mode

### ISSUE THREAD

**Issue by pauluss** [germanfr/cinnamon-transparent-panels#37]
UUID: transparent-panels@germanfr: Panels extension in Cinnamon: hardly different colors in panel edit mode

```
 * Extension version: Version 4.0~20181106 (2019-12-27 09:42:37)
 * Cinnamon version: Cinnamon 4.4.8

 ```

**Describe the bug**
When in panel edit mode, there should be three different colors in the panel/taskbar, to represent the three different Zones: Left Zone, Centre Zone and Right Zone.

Those three different colors show where the three Zones are: where they start and end, in order to drag and drop the several items/icons in the desired Zones.

The colors are normally bright and very easy to distinguish, but when the extension Transparent Panels is on, these color are very hard to distinguish.

Solution: to edit Transparent Panels in order to show the three colors in panel edit mode, as if Transparent Panels were not loaded/on.

palbertsma@gmail.com

**Comment by germanfr** [comment]
Thanks for the tip. You can already do that overriding your themes as it is explained in the readme. Alternatively, if your background is very bright, you can use the shadow option (which can be customized too).
