### ISSUE TITLE
Error: Cinnamon-Tranparent panel

### ISSUE THREAD

**Issue by stummerwinter** [germanfr/cinnamon-transparent-panels#42]
```
 * Extension version: (click info in extension settings)
 * Cinnamon version: 4.6.7
 * Attach log:       
error t=2020-10-15T09:34:24Z Fehler beim Öffnen der Datei »/usr/share/cinnamon/extensions/transparent-panels@germanfr/metadata.json«: Keine Berechtigung

error t=2020-10-15T09:34:24Z [transparent-panels@germanfr]: Missing property "uuid" in metadata.json[
 ```

**Steps to reproduce**

After fresh installation RebornOS got directly this error

**Other information**

Lenovo T420

```
                             stumerwinter@RebornT420
                             OS: rebornos 
                             Kernel: x86_64 Linux 5.8.14-arch1-1
         #####               Uptime: 14m
        #######              Packages: Unknown
        ##O#O##              Shell: bash 5.0.18
        #######              Resolution: 1920x1080
      ###########            DE: Cinnamon 4.6.7
     #############           WM: Muffin
    ###############          WM Theme: macOS-Arc-White (MacOS-Sierra)
    ################         GTK Theme: elementary [GTK2/3]
   #################         Icon Theme: elementary
 #####################       Font: Sans 9
 #####################       Disk: 12G / 55G (23%)
   #################         CPU: Intel Core i5-2520M @ 4x 3.2GHz [48.0°C]
                             GPU: Mesa DRI Intel(R) HD Graphics 3000 (SNB GT2)
                             RAM: 1702MiB / 3814MiB
```

**Comment by stummerwinter** [comment]
Edit: the error comes direct after fresh install

After Install of Transparent Panels Extension the error is gone

**Comment by germanfr** [comment]
The `uuid` key actually exists in the `metadata.json` ([see here](https://github.com/germanfr/cinnamon-transparent-panels/blob/8b98f07a539e78e1265e021e97fff84d65c355e1/transparent-panels%40germanfr/metadata.json#L17)). Maybe somehow you or something you installed in your system changed it, or it's a Cinnamon bug.

As the error states, there is no `uuid` in this file: `/usr/share/cinnamon/extensions/transparent-panels@germanfr/metadata.json`, so you can add it or replace the file with the one of the link above.

**Comment by stummerwinter** [comment]
Thank you for the response...

The error occurs after fresh install without touching the system...so maybe a Cinnamon-bug, that's why I posted here...

There is no file metadata.jason...just after fresh install the OS...after manual installation of transparent panels the error ist gone, need to check if metadata.json ist now there...

**Comment by germanfr** [comment]
If the extension comes preinstalled, then you should report it to the maintainer of the distribution you are using. More so, if you say the issue is gone after installing the extension from the official distribution channel (that is, the Cinnamon Spices integrated in the Cinnamon settings).
