### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by NikoKrause** [germanfr/cinnamon-transparent-panels#5]
Hey,

maybe you could add translation support. I added a German translation.
It suffices to unzip the attached po directory into your extensions directory.

[po.zip](https://github.com/germanfr/cinnamon-transparent-panels/files/705910/po.zip)

If you need more info, let me know.

**Comment by germanfr** [comment]
Yes I need more info. Because I actually don't know how to do it.

**Comment by NikoKrause** [comment]
OK. Download the po.zip file. Extract it. Move the extracted `po` directory in your `transparent-panels@germanfr` directory, it means where the metadata.json file is stored. That's it.

Now if you want to create and test a new translation: Here is a small tutorial:

https://github.com/Odyseus/CinnamonTools/wiki/Xlet-localizations

**Comment by germanfr** [comment]
Ok thanks. It wasn't that hard :sweat_smile:  I learned today that nouns are capitalized in German.

I already pushed it. Can you tell me if it works?

**Comment by NikoKrause** [comment]
Thanks. I'll try it asap and let you know.

**Comment by NikoKrause** [comment]
It's working! Thanks.
